name: Build darkice CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: autogen
      run: ./autogen.sh
      working-directory: ./darkice
    - name: configure
      run: ./configure
      working-directory: ./darkice
    - name: make
      run: make -j
      working-directory: ./darkice
    - name: make check
      run: make check
      working-directory: ./darkice
    - name: make distcheck
      run: make distcheck
      working-directory: ./darkice
